# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of Liu Yubao
email: yubaoliu89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        This blog is build using Jekyll and Emacs ORG.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yubaoliu.github.io" # the base hostname & protocol for your site
twitter_username: yubaoliu
github_username:  yubaoliu
linkedin: https://www.linkedin.com/in/yubao-liu-1022b7120/
instagram:

elasticsearch:
 url: "https://fhridvgup:99v9wkn7bv@blog-7074892904.ap-southeast-2.bonsaisearch.net:443"
 index_name: blog 

algolia:
 application_id: 'W2P30L7YW7'
 index_name: yubao_blog
 search_only_api_key: 069c62cf17f604d26e82360e8e5a1dbd

# Build settings
markdown: kramdown

kramdown:
 input: GFM
 extensions:
  - footnotes
  - smart
 auto_ids: true
 footnote_nr: 1
 entity_output: as_char
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 coderay_line_numbers: table
 coderay_tab_width: 4
 line_width: 100


#Plugin Setting
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-figure
  - jekyll-gist
  - jekyll-coffeescript
  - jemoji
  - jekyll-redirect-from
  - jekyll-algolia
  - searchyll

filter: 'category'
recent_num: 20


jekyll-figure:
  paragraphs: false

# disqus config
disqus: https-yubaoliu-github-io
comments: true

# google analytics config
ga:
  id: UA-131527698-1
  url: yubaoliu.github.io

sass:
  style: compressed


defaults:
 - scope:
         path: "img"
   values:
        image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
