# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of Liu Yubao
email: yubaoliu89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        This blog is build using Jekyll and Emacs ORG.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yubaoliu.github.io" # the base hostname & protocol for your site
twitter_username: yubaoliu
github_username:  yubaoliu
linkedin: https://www.linkedin.com/in/yubao-liu-1022b7120/
instagram:

# Build settings
markdown: kramdown

kramdown:
 input: GFM
 extensions:
  - autolink
  - footnotes
  - smart
 auto_ids: true
 footnote_nr: 1
 entity_output: as_char
 toc_levels: 1..4
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 coderay_line_numbers: table
 coderay_tab_width: 4
 line_width: 80
 latex_headers: section,subsection,subsubsection,paragraph,subparagraph,subparagraph


#Plugin Setting
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-figure
  - jekyll-gist
  - jekyll-coffeescript
  - jemoji
  - jekyll-redirect-from

filter: 'category'
recent_num: 20


toc:
  min_level: 1
  max_level: 3
  list_class: section-nav
  no_toc_section_class: exclude # default: no_toc_section


jekyll-figure:
  paragraphs: false

# disqus config
disqus: https-yubaoliu-github-io
comments: true

# google analytics config
ga:
  id: UA-131527698-1
  url: yubaoliu.github.io

sass:
  style: compressed


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Liu Yubao
      csl: ../assets/ieee.cls
      bibliography: ../assets/bibliography/bibliography.bib


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
