* Important Notes
  :PROPERTIES:
  :CUSTOM_ID: important-notes
  :END:

- Only support kramdown GitHub Pages only supports kramdown as a
  Markdown processor. Refer
  [[https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/][Updating
  your Markdown processor to kramdown]] for detail. If you use *pandoc*,
  rather tan *kramdown*, you may receive this warning:

  #+BEGIN_QUOTE
    The page build completed successfully, but returned the following
    warning for the =master= branch: You are currently using the
    'pandoc' Markdown engine, which is no longer supported by GitHub
    Pages and may cease working at any time. To ensure your site
    continues to build, remove the 'markdown' setting in your site's
    '_config.yml' file and confirm your site renders as expected. For
    more information, see
    https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.
    For information on troubleshooting Jekyll see:
    https://help.github.com/articles/troubleshooting-jekyll-builds If
    you have any questions you can contact us by replying to this email.
  #+END_QUOTE

* Install and Usage
  :PROPERTIES:
  :CUSTOM_ID: install-and-usage
  :END:

- [[https://jekyllrb.com/docs/][jekyllrb-doc]]

#+BEGIN_SRC python
    sudo apt-get install ruby-full build-essential zlib1g-dev
    echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
    echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
    echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
    source ~/.bashrc
#+END_SRC

** Run server
   :PROPERTIES:
   :CUSTOM_ID: run-server
   :END:

=sh bundle exec jekyll serve  --watch=

* Frontmatter
  :PROPERTIES:
  :CUSTOM_ID: frontmatter
  :END:

permalink: /:categories/:year/:month/:day/:title.html (.php)

* Themes
  :PROPERTIES:
  :CUSTOM_ID: themes
  :END:

** Deploy your theme
   :PROPERTIES:
   :CUSTOM_ID: deploy-your-theme
   :END:

1. Download from [[https://rubygems.org/][RubygemsThemes]] or
   [[http://jekyllthemes.org/][jekyllthemes]]
2. Search =jekyll-theme=
3. vim /gemfile/: =gem "classic-jekyll-theme"=
4. Run =bundle install=
5. Vim *_config.yaml*: =theme: classic-jekyll-theme=

** Recommeded Themes
   :PROPERTIES:
   :CUSTOM_ID: recommeded-themes
   :END:

1. [[https://llawlight.github.io/bohu-jekyll-theme/][bohu-jekyll-theme]]
2. [[https://github.com/Balancingrock/classic-jekyll-theme][classic-jekyll-theme]]
3. [[https://github.com/suyan/suyan.github.io][suyan/suyan.github.io]]

* Grammer
  :PROPERTIES:
  :CUSTOM_ID: grammer
  :END:

** Loop
   :PROPERTIES:
   :CUSTOM_ID: loop
   :END:

#+BEGIN_EXAMPLE
    {% for post in site.posts %}
      {{ post.title }} <br>
    {% endfor %}
#+END_EXAMPLE

** Condition sentence
   :PROPERTIES:
   :CUSTOM_ID: condition-sentence
   :END:

=or= and =and= can be used in condition

#+BEGIN_EXAMPLE
    {% if page.title == "My First Post" %}
      This is the first post
    {% elsif page.title == "My Second Post" %}
      This is the second post
    {% else %}
        This is another post
    {% endif %}
#+END_EXAMPLE

** Access yml file
   :PROPERTIES:
   :CUSTOM_ID: access-yml-file
   :END:

_data/people.yml:

#+BEGIN_EXAMPLE
    - name: "name-A"
      occupation: "O-A"
    - name: "naeme-B"
      occupation: "O-B"
    - name: "konan"
      occupation: "tantei"
#+END_EXAMPLE

home.html:

#+BEGIN_EXAMPLE
    \{\% for person in site.data.people %}
      \{\{ person.name }}, {{ person.occupation }}
    \{\% endfor %}
#+END_EXAMPLE

** Access static_files
   :PROPERTIES:
   :CUSTOM_ID: access-static_files
   :END:

#+BEGIN_EXAMPLE
    \{\% for file in site.static_files %}
      \{\{ file.path}} <br>
    \{\% endfor %}
#+END_EXAMPLE

- /file.basename/
- /file.extname/

* Math - Latex
  :PROPERTIES:
  :CUSTOM_ID: math---latex
  :END:

Refer 1.
[[https://lyk6756.github.io/2016/11/25/write_latex_equations.html][Write
LaTeX Equations in Jekyll Using MathJax & Kramdown]] 2.
[[http://docs.mathjax.org/en/latest/start.html#using-a-content-delivery-network-cdn]]

* Images
  :PROPERTIES:
  :CUSTOM_ID: images
  :END:

/image.html/:

#+BEGIN_EXAMPLE
    <img src="{{ include.file }}" alt="{{ include.description }}">
    <span class="caption">{{ include.description }}</span>
#+END_EXAMPLE

Including the file:

#+BEGIN_SRC sh
    ---
    layout: post
    title: Image Caption Example
    ---

    \{\% include image.html file="img.jpg" description="Triangle_area_from_coordinates" \%\}
#+END_SRC

{% include image.html
file="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Triangle_area_from_coordinates_JCB.jpg/732px-Triangle_area_from_coordinates_JCB.jpg"
description="This is an image." height="240" weight="320" %}

** Reference
   :PROPERTIES:
   :CUSTOM_ID: reference
   :END:

- [[https://www.kevinmcgillivray.net/captions-for-images-with-jekyll/][How
  to Create Image Captions with Jekyll]]

#+BEGIN_HTML
  <hr>
#+END_HTML

* Original Example
  :PROPERTIES:
  :CUSTOM_ID: original-example
  :END:

You'll find this post in your =_posts= directory. Go ahead and edit it
and re-build the site to see your changes. You can rebuild the site in
many different ways, but the most common way is to run =jekyll serve=,
which launches a web server and auto-regenerates your site when a file
is updated.

To add new posts, simply add a file in the =_posts= directory that
follows the convention =YYYY-MM-DD-name-of-post.ext= and includes the
necessary front matter. Take a look at the source for this post to get
an idea about how it works.

Jekyll also offers powerful support for code snippets:

{% highlight ruby %} def print_hi(name) puts "Hi, #{name}" end
print_hi('Tom') #=> prints 'Hi, Tom' to STDOUT. {% endhighlight %}

Check out the [[https://jekyllrb.com/docs/home][Jekyll docs]] for more
info on how to get the most out of Jekyll. File all bugs/feature
requests at [[https://github.com/jekyll/jekyll][Jekyll's GitHub repo]].
If you have questions, you can ask them on
[[https://talk.jekyllrb.com/][Jekyll Talk]].
