* 2018

** MID-Fusion: Octree-based Object-Level Multi-Instance Dynamic SLAM
   :PROPERTIES:
   :CUSTOM_ID: mid-fusion-octree-based-object-level-multi-instance-dynamic-slam
   :END:

- [[https://youtu.be/Be_Ndceb2VI][Youtube-Demo]]

#+BEGIN_EXAMPLE
    @article{xu2018mid,
      title={MID-Fusion: Octree-based Object-Level Multi-Instance Dynamic SLAM},
      author={Xu, Binbin and Li, Wenbin and Tzoumanikas, Dimos and Bloesch, Michael and Davison, Andrew and Leutenegger, Stefan},
      journal={arXiv preprint arXiv:1812.07976},
      year={2018}
    }
#+END_EXAMPLE

** Fusion++: Volumetric Object-Level SLAM
fusion-volumetric-object-level-slam

体积对象级SLAM

- [[https://www.doc.ic.ac.uk/~sleutene/publications/fusion_plusplus_3dv_camera_ready.pdf][Paper-PDF]]

- [[https://github.com/matterport/Mask_RCNN][matterport/Mask_RCNN]] This
  is an implementation of Mask R-CNN on Python 3, Keras, and TensorFlow.
  The model generates bounding boxes and segmentation masks for each
  instance of an object in the image. It's based on Feature Pyramid
  Network (FPN) and a ResNet101 backbone.
- [[https://github.com/andyzeng/tsdf-fusion][andyzeng/tsdf-fusion]]
  CUDA/C++ code to fuse multiple registered depth maps into a projective
  truncated signed distance function (TSDF) voxel volume, which can then
  be used to create high quality 3D surface meshes and point clouds.
  Tested on Ubuntu 14.04 and 16.04.

- [[https://github.com/tensorpack/tensorpack][tensorpack/tensorpack]]

- [[https://www.youtube.com/embed/2luKNC03x4k][Demo-Youtube]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/2luKNC03x4k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

- cite:

McCormac, John, et al. "Fusion++: Volumetric object-level slam." 2018
International Conference on 3D Vision (3DV). IEEE, 2018.

- Authors

John McCormac∗ Ronald Clark∗ Michael Bloesch Andrew J. Davison Stefan
Leutenegger Dyson Robotics Laboratory Department of Computing, Imperial
College London

** CodeSLAM --- Learning a Compact, Optimisable Representation for Dense
Visual SLAM
   :PROPERTIES:
   :CUSTOM_ID: codeslam-learning-a-compact-optimisable-representation-for-dense-visual-slam
   :END:

** CubeSLAM: Monocular 3D Object Detection and SLAM without Prior Models
   :PROPERTIES:
   :CUSTOM_ID: cubeslam-monocular-3d-object-detection-and-slam-without-prior-models
   :END:

- Authors: Shichao Yang, Sebastian Scherer
- Robotics Institute, Carnegie Mellon University
- {fshichaoy, bastig}@andrew.cmu.edu
- [[https://github.com/shichaoy/cube_slam][Github-shichaoy/cube_slam]],
  with ROS

  This code contains a basic implementation for Cube SLAM. Given RGB and
  2D object detection, the algorithm detects 3D cuboids from each frame
  then formulate an object SLAM to optimize both camera pose and cuboid
  poses.
- [[https://youtu.be/QnVlexXi9_c][youtube-demo]]

#+BEGIN_HTML
  <iframe width="640" height="508" src="https://www.youtube.com/embed/QnVlexXi9_c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

#+BEGIN_EXAMPLE
    @article{yang2018cubeslam,
      title={CubeSLAM: Monocular 3D Object Detection and SLAM without Prior Models},
      author={Yang, Shichao and Scherer, Sebastian},
      journal={arXiv preprint arXiv:1806.00557},
      year={2018}
    }
#+END_EXAMPLE

** DynaSLAM: Tracking, Mapping and Inpainting in Dynamic Scenes
   :PROPERTIES:
   :CUSTOM_ID: dynaslam-tracking-mapping-and-inpainting-in-dynamic-scenes
   :END:

- [[https://github.com/BertaBescos/DynaSLAM][Github-BertaBescos/DynaSLAM]]
- [[https://bertabescos.github.io/DynaSLAM/][project]]
- [[https://youtu.be/EabI_goFmQs][Demo-Youtube]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/EabI_goFmQs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

#+BEGIN_EXAMPLE
    @inproceedings{bescos2018dynaslam,
      author = {Bescos, Berta and F{\'a}cil, Jos{\'e} M. and Civera, Javier and Neira, Jos{\'e}},
      title = {{DynaSLAM: Tracking, Mapping and Inpainting in Dynamic Scenes}},
      journal = {arXiv},
      year = {2018}
    }
#+END_EXAMPLE

** Monocular Object and Plane SLAM in Structured Environments
   :PROPERTIES:
   :CUSTOM_ID: monocular-object-and-plane-slam-in-structured-environments
   :END:

- [[https://arxiv.org/pdf/1809.03415.pdf][paper-pdf]]

#+BEGIN_EXAMPLE
    @article{yang2018monocular,
      title={Monocular Object and Plane SLAM in Structured Environments},
      author={Yang, Shichao and Scherer, Sebastian},
      journal={arXiv preprint arXiv:1809.03415},
      year={2018}
    }
#+END_EXAMPLE

- [[https://youtu.be/jzBMsKCm0uk][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="508" src="https://www.youtube.com/embed/jzBMsKCm0uk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** Deep Learning Based Semantic Labelling of 3D Point Cloud in Visual
SLAM
   :PROPERTIES:
   :CUSTOM_ID: deep-learning-based-semantic-labelling-of-3d-point-cloud-in-visual-slam
   :END:

- [[https://github.com/qixuxiang/orb-slam2_with_semantic_label][Github-qixuxiang/orb-slam2_with_semantic_label]]
- [[https://github.com/qixuxiang/real_time_object_detect][Github-qixuxiang/real_time_object_detect]]
- [[https://github.com/AmeyaWagh/3D_object_recognition][AmeyaWagh/3D_object_recognition]]
  recognize and localize an object in 3D Point Cloud scene using 3D-CNNs

#+BEGIN_EXAMPLE
    @inproceedings{qi2018deep,
      title={Deep Learning Based Semantic Labelling of 3D Point Cloud in Visual SLAM},
      author={Qi, Xuxiang and Yang, Shaowu and Yan, Yuejin},
      booktitle={IOP Conference Series: Materials Science and Engineering},
      volume={428},
      number={1},
      pages={012023},
      year={2018},
      organization={IOP Publishing}
    }
#+END_EXAMPLE

** CNN-SVO: Improving the Mapping in Semi-Direct Visual Odometry Using
Single-Image Depth Prediction
   :PROPERTIES:
   :CUSTOM_ID: cnn-svo-improving-the-mapping-in-semi-direct-visual-odometry-using-single-image-depth-prediction
   :END:

- [[https://github.com/yan99033/CNN-SVO][Github-yan99033/CNN-SVO]]
  support ROS
- [[https://github.com/yan99033/monodepth-cpp][Github-yan99033/monodepth-cpp]]
  Tensorflow C++ implementation for single image depth estimation
- [[https://www.youtube.com/watch?v=4oTzwoby3j][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/4oTzwoby3jw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** UnDeepVO: Monocular Visual Odometry through Unsupervised Deep
Learning
   :PROPERTIES:
   :CUSTOM_ID: undeepvo-monocular-visual-odometry-through-unsupervised-deep-learning
   :END:

- [[https://github.com/drmaj/UnDeepVO][Github-drmaj/UnDeepVO]] The
  implementation is not working yet. Once it is complete, the README
  will be updated with a full description and usage directions.
- Paper: https://arxiv.org/pdf/1709.06841v1.pdf
- Project Website: http://senwang.gitlab.io/UnDeepVO/
- [[https://youtu.be/5RdjO93wJqo][youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/5RdjO93wJqo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** Unsupervised Learning of Monocular Depth Estimation and Visual
Odometry with Deep Feature Reconstruction
   :PROPERTIES:
   :CUSTOM_ID: unsupervised-learning-of-monocular-depth-estimation-and-visual-odometry-with-deep-feature-reconstruction
   :END:

#+BEGIN_EXAMPLE
    @InProceedings{Zhan_2018_CVPR,
    author = {Zhan, Huangying and Garg, Ravi and Saroj Weerasekera, Chamara and Li, Kejie and Agarwal, Harsh and Reid, Ian},
    title = {Unsupervised Learning of Monocular Depth Estimation and Visual Odometry With Deep Feature Reconstruction},
    booktitle = {The IEEE Conference on Computer Vision and Pattern Recognition (CVPR)},
    month = {June},
    year = {2018}
    }
#+END_EXAMPLE

- [[file:Huangying-Zhan/Depth-VO-Feat][Github]]
- [[https://huangying-zhan.github.io/][Huangying Zhan / 粘煌熒]]

** Fast and Accurate Semantic Mapping through Geometric-based
Incremental Segmentation
   :PROPERTIES:
   :CUSTOM_ID: fast-and-accurate-semantic-mapping-through-geometric-based-incremental-segmentation
   :END:

- [[https://youtu.be/nYG8jqFBqWI][youtube-demo]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/nYG8jqFBqWI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** Real-Time Object Pose Estimation with Pose Interpreter Networks
   :PROPERTIES:
   :CUSTOM_ID: real-time-object-pose-estimation-with-pose-interpreter-networks
   :END:

- [[https://github.com/jimmyyhwu/pose-interpreter-networks][Github-jimmyyhwu/pose-interpreter-networks]]
- [[https://youtu.be/9QBw1NCOOR0][youtube-demo]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/9QBw1NCOOR0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

#+BEGIN_EXAMPLE
    @INPROCEEDINGS{wu2018pose,
    author={J. Wu and B. Zhou and R. Russell and V. Kee and S. Wagner and M. Hebert and A. Torralba and D. M. S. Johnson},
    booktitle={2018 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)},
    title={Real-Time Object Pose Estimation with Pose Interpreter Networks},
    year={2018},
    volume={},
    number={},
    pages={6798-6805},
    keywords={Pose estimation;Image segmentation;Three-dimensional displays;Quaternions;Real-time systems;Training;Task analysis},
    doi={10.1109/IROS.2018.8593662},
    ISSN={2153-0866},
    month={Oct},}
#+END_EXAMPLE

** BiSeNet:Bilateral Segmentation Network for Real-time Semantic
Segmentation
   :PROPERTIES:
   :CUSTOM_ID: bisenetbilateral-segmentation-network-for-real-time-semantic-segmentation
   :END:

- [[https://github.com/Shuai-Xie/BiSeNet-CCP][Github-Shuai-Xie/BiSeNet-CCP]]

** SfMLearner++: Learning Monocular Depth & Ego-Motion using Meaningful
Geometric Constraints
   :PROPERTIES:
   :CUSTOM_ID: sfmlearner-learning-monocular-depth-ego-motion-using-meaningful-geometric-constraints
   :END:

- [[https://arxiv.org/pdf/1812.08370.pdf][paper-pdf]]
- [[file:SfMLearner++:%20Learning%20Monocular%20Depth%20&%20Ego-Motion%20using%20Meaningful%20Geometric%20Constraints][Githut-tinghuiz/SfMLearner]]

** Deep Virtual Stereo Odometry: Leveraging Deep Depth Prediction for
Monocular Direct Sparse Odometry
   :PROPERTIES:
   :CUSTOM_ID: deep-virtual-stereo-odometry-leveraging-deep-depth-prediction-for-monocular-direct-sparse-odometry
   :END:

- [[https://youtu.be/sLZOeC9z_tw][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/sLZOeC9z_tw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

* 2017
  :PROPERTIES:
  :CUSTOM_ID: section-1
  :END:

** 2017-Fast Incremental Bundle Adjustment with Covariance Recovery
   :PROPERTIES:
   :CUSTOM_ID: fast-incremental-bundle-adjustment-with-covariance-recovery
   :END:

- [[https://youtu.be/PG9X9k7KXRo][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640 " height="480" src="https://www.youtube.com/embed/PG9X9k7KXRo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** BundleFusion: Real-time Globally Consistent 3D Reconstruction using
On the-fly Surface Reintegration
   :PROPERTIES:
   :CUSTOM_ID: bundlefusion-real-time-globally-consistent-3d-reconstruction-using-on-the-fly-surface-reintegration
   :END:

- [[https://youtu.be/keIirXrRb1k][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/keIirXrRb1k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

- [[http://graphics.stanford.edu/projects/bundlefusion/][Project]]
- [[https://github.com/niessner/BundleFusion][Github-niessner/BundleFusion]]

** Scenenet rgb-d: Can 5m synthetic images beat generic imagenet
pre-training on indoor segmentation
   :PROPERTIES:
   :CUSTOM_ID: scenenet-rgb-d-can-5m-synthetic-images-beat-generic-imagenet-pre-training-on-indoor-segmentation
   :END:

#+BEGIN_EXAMPLE
    @inproceedings{mccormac2017scenenet,
      title={Scenenet rgb-d: Can 5m synthetic images beat generic imagenet pre-training on indoor segmentation},
      author={McCormac, John and Handa, Ankur and Leutenegger, Stefan and Davison, Andrew J},
      booktitle={Proceedings of the International Conference on Computer Vision (ICCV)},
      volume={4},
      year={2017}
    }
#+END_EXAMPLE

- [[https://bitbucket.org/dysonroboticslab/scenenetrgb-d/src/master/][Bitbucket-Dyson
  Robotics Lab/SceneNetRGB-D]]

** 3DMatch: Learning Local Geometric Descriptors from RGB-D
Reconstructions
   :PROPERTIES:
   :CUSTOM_ID: dmatch-learning-local-geometric-descriptors-from-rgb-d-reconstructions
   :END:

- [[https://arxiv.org/pdf/1603.08182.pdf][Paper-pdf]]

#+BEGIN_EXAMPLE
    @inproceedings{zeng20163dmatch,
        title={3DMatch: Learning Local Geometric Descriptors from RGB-D Reconstructions},
        author={Zeng, Andy and Song, Shuran and Nie{\ss}ner, Matthias and Fisher, Matthew and Xiao, Jianxiong and Funkhouser, Thomas},
        booktitle={CVPR},
        year={2017}
    }
#+END_EXAMPLE

- [[http://3dmatch.cs.princeton.edu/][3DMatch: Learning Local Geometric
  Descriptors from RGB-D Reconstructions]]

- [[https://github.com/andyzeng/3dmatch-toolbox][andyzeng/3dmatch-toolbox]]
  3DMatch is a ConvNet-based local geometric feature descriptor that
  operates on 3D data (i.e. point clouds, depth maps, meshes, etc.).
  This toolbox provides code to use 3DMatch for geometric registration
  and keypoint matching, as well as code to train 3DMatch from existing
  RGB-D reconstructions. This is the reference implementation of our
  paper:

- [[https://youtu.be/gZrsJJtDvvA][Demo-Youtube]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/gZrsJJtDvvA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

- [[https://youtu.be/qNVZl7bCjsU?list=PL_bDvITUYucADb15njRd7geem8vxOyo6N][Presentation-Youtube]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/qNVZl7bCjsU?list=PL_bDvITUYucADb15njRd7geem8vxOyo6N" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** SemanticFusion: Dense 3D Semantic Mapping with Convolutional Neural
Networks
   :PROPERTIES:
   :CUSTOM_ID: semanticfusion-dense-3d-semantic-mapping-with-convolutional-neural-networks
   :END:

#+BEGIN_EXAMPLE
    @inproceedings{mccormac2017semanticfusion,
      title={Semanticfusion: Dense 3d semantic mapping with convolutional neural networks},
      author={McCormac, John and Handa, Ankur and Davison, Andrew and Leutenegger, Stefan},
      booktitle={2017 IEEE International Conference on Robotics and automation (ICRA)},
      pages={4628--4635},
      year={2017},
      organization={IEEE}
    }
#+END_EXAMPLE

- [[https://bitbucket.org/dysonroboticslab/semanticfusion/src/master/][Bitbucket-Dyson
  Robotics Lab/SemanticFusion]]
- [[https://youtu.be/cGuoyNY54kU][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="604" src="https://www.youtube.com/embed/cGuoyNY54kU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

* 2016
  :PROPERTIES:
  :CUSTOM_ID: section-2
  :END:

** 2016-Pairwise Decomposition of Image Sequences for Active Multi-View
Recognition
   :PROPERTIES:
   :CUSTOM_ID: pairwise-decomposition-of-image-sequences-for-active-multi-view-recognition
   :END:

#+BEGIN_EXAMPLE
    @inproceedings{johns2016pairwise,
      title={Pairwise decomposition of image sequences for active multi-view recognition},
      author={Johns, Edward and Leutenegger, Stefan and Davison, Andrew J},
      booktitle={Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition},
      pages={3813--3822},
      year={2016}
    }
#+END_EXAMPLE

- [[https://youtu.be/7Bw0HGlidtg][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/7Bw0HGlidtg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
#+END_HTML

** ElasticFusion: Real-Time Dense SLAM and Light Source Estimation

- [[https://bitbucket.org/dysonroboticslab/semanticfusion/src/master/][Bitbucket-Dyson
  Robotics Lab/SemanticFusion]]
- [[https://github.com/mp3guy/ElasticFusion][mp3guy/ElasticFusion]]

#+BEGIN_EXAMPLE
    @article{whelan2016elasticfusion,
      title={ElasticFusion: Real-time dense SLAM and light source estimation},
      author={Whelan, Thomas and Salas-Moreno, Renato F and Glocker, Ben and Davison, Andrew J and Leutenegger, Stefan},
      journal={The International Journal of Robotics Research},
      volume={35},
      number={14},
      pages={1697--1716},
      year={2016},
      publisher={SAGE Publications Sage UK: London, England}
    }
#+END_EXAMPLE

- [[https://youtu.be/QFDnFjV9YdM][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/QFDnFjV9YdM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
#+END_HTML

** Slam with objects using a nonparametric pose graph
- [[https://github.com/BeipengMu/objectSLAM][Github-BeipengMu/objectSLAM]]
- [[http://people.csail.mit.edu/kaess/][Dr. Michael Kaess]]
- [[https://arxiv.org/pdf/1704.05959.pdf][paper-pdf]]
- [[https://youtu.be/YANUWdVLJD4][Demo-Youtube]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/YANUWdVLJD4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
#+END_HTML

#+BEGIN_EXAMPLE
    @inproceedings{mu2016slam,
      title={Slam with objects using a nonparametric pose graph},
      author={Mu, Beipeng and Liu, Shih-Yuan and Paull, Liam and Leonard, John and How, Jonathan P},
      booktitle={Intelligent Robots and Systems (IROS), 2016 IEEE/RSJ International Conference on},
      pages={4602--4609},
      year={2016},
      organization={IEEE}
    }
#+END_EXAMPLE

** Pop-up SLAM: Semantic Monocular Plane SLAM for Low-texture
- [[https://github.com/shichaoy/pop_up_slam][Github-shichaoy/pop_up_slam]]

- [[https://youtu.be/TOSOWdxmtkw][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/TOSOWdxmtkw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
#+END_HTML

** Real-time 3D scene layout from a single image using convolutional
- [[https://www.ri.cmu.edu/pub_files/2016/5/icra_2016.pdf][Paper]]
- [[https://youtu.be/2CvFHy5jk1c][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="800" height="450" src="https://www.youtube.com/embed/2CvFHy5jk1c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
#+END_HTML

** 2015-SLAM++: Simultaneous Localisation and Mapping at the Level of Objecs

- [[https://github.com/tolgabirdal/ppf_matching][Github-tolgabirdal/ppf_matching]]
-

*** Monocular SLAM Supported Object Recognition

- [[https://people.csail.mit.edu/spillai/projectsvslam-object-recognition/pillai_rss15_poster.pdf][post]]
- [[http://people.csail.mit.edu/spillai/projectsi/vslam-object-recognition/][project]]
- [[http://www.roboticsproceedings.org/rss11/p34.pdf][paper]]

** PoseNet: A Convolutional Network for Real-Time 6-DOF Camera
Relocalization
   :PROPERTIES:
   :CUSTOM_ID: posenet-a-convolutional-network-for-real-time-6-dof-camera-relocalization
   :END:

- [[https://github.com/alexgkendall/caffe-posenet][alexgkendall/caffe-posenet]]
- [[https://github.com/kentsommer/tensorflow-posenet][kentsommer/tensorflow-posenet]]
- [[https://youtu.be/u0MVbL_RyPU][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/u0MVbL_RyPU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

** Robot In a Room: Toward Perfect Object Recognition in Closed
Environments
   :PROPERTIES:
   :CUSTOM_ID: robot-in-a-room-toward-perfect-object-recognition-in-closed-environments
   :END:

* 2014
  :PROPERTIES:
  :CUSTOM_ID: section-4
  :END:

** Semantic Localization Via the Matrix Permanent
   :PROPERTIES:
   :CUSTOM_ID: semantic-localization-via-the-matrix-permanent
   :END:

#+BEGIN_EXAMPLE
    @inproceedings{atanasov2014semantic,
    title={Semantic Localization Via the Matrix Permanent.},
    author={Atanasov, Nikolay and Zhu, Menglong and Daniilidis, Kostas and Pappas, George J},
    booktitle={Robotics: Science and Systems},
    volume={2},
    year={2014}
    }
#+END_EXAMPLE

- [[https://youtu.be/P3JuOT6kKM0][youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/P3JuOT6kKM0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

* 2013
  :PROPERTIES:
  :CUSTOM_ID: section-5
  :END:

** Scene Coordinate Regression Forests for Camera Relocalization in
RGB-D Images
   :PROPERTIES:
   :CUSTOM_ID: scene-coordinate-regression-forests-for-camera-relocalization-in-rgb-d-images
   :END:

- [paper-pdf]

#+BEGIN_EXAMPLE
    @Inprceedings {export:184826,
    author       = {Jamie Shotton and Ben Glocker and Christopher Zach and Shahram Izadi and Antonio
                    Criminisi and Andrew Fitzgibbon},
    booktitle    = {Proc. Computer Vision and Pattern Recognition (CVPR)},
    month        = {June},
    publisher    = {IEEE},
    title        = {Scene Coordinate Regression Forests for Camera Relocalization in RGB-D Images},
    url          = {http://research.microsoft.com/apps/pubs/default.aspx?id=184826},
    year         = {2013},
    }
#+END_EXAMPLE

- [[https://github.com/ISUE/relocforests][Github-ISUE/relocforests]]

* 2012
  :PROPERTIES:
  :CUSTOM_ID: section-6
  :END:

** Semantic Structure From Motion with Points, Regions, and Objects
   :PROPERTIES:
   :CUSTOM_ID: semantic-structure-from-motion-with-points-regions-and-objects
   :END:

- [[https://youtu.be/rO6-mz1OVH8][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="555" src="https://www.youtube.com/embed/rO6-mz1OVH8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

* 2011
  :PROPERTIES:
  :CUSTOM_ID: section-7
  :END:

** KinectFusion: Real-Time Dense Surface Mapping and Tracking
   :PROPERTIES:
   :CUSTOM_ID: kinectfusion-real-time-dense-surface-mapping-and-tracking
   :END:

- [[https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/ismar2011.pdf][paper-pdf]]

- [[https://github.com/chrdiller/KinectFusionLib][chrdiller/KinectFusionLib]]

- [[https://youtu.be/KOUSSlKUJ-A][Youtube-Demo]]

#+BEGIN_HTML
  <iframe width="640" height="480" src="https://www.youtube.com/embed/KOUSSlKUJ-A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
#+END_HTML

#+BEGIN_HTML
  </iframe>
#+END_HTML

#+BEGIN_EXAMPLE
    @inproceedings{newcombe2011kinectfusion,
      title={KinectFusion: Real-time dense surface mapping and tracking},
      author={Newcombe, Richard A and Izadi, Shahram and Hilliges, Otmar and Molyneaux, David and Kim, David and Davison, Andrew J and Kohi, Pushmeet and Shotton, Jamie and Hodges, Steve and Fitzgibbon, Andrew},
      booktitle={Mixed and augmented reality (ISMAR), 2011 10th IEEE international symposium on},
      pages={127--136},
      year={2011},
      organization={IEEE}
    }
#+END_EXAMPLE

** Towards Semantic SLAM using a Monocular Camera
   :PROPERTIES:
   :CUSTOM_ID: towards-semantic-slam-using-a-monocular-camera
   :END:

#+BEGIN_EXAMPLE
    @inproceedings{civera2011towards,
    title={Towards semantic SLAM using a monocular camera},
    author={Civera, Javier and G{\'a}lvez-L{\'o}pez, Dorian and Riazuelo, Luis and Tard{\'o}s, Juan D and Montiel, JMM},
    booktitle={Intelligent Robots and Systems (IROS), 2011 IEEE/RSJ International Conference on},
    pages={1277--1284},
    year={2011},
    organization={IEEE}
    }
#+END_EXAMPLE

** SSFM-Semantic Structure From Motion
   :PROPERTIES:
   :CUSTOM_ID: ssfm-semantic-structure-from-motion
   :END:

- [[http://vhosts.eecs.umich.edu/vision//projects/ssfm/index.html][project]]

#+BEGIN_EXAMPLE
    @article{bao2011semantic,
      title={Semantic structure from motion},
      author={Bao, Sid Yingze and Savarese, Silvio},
      year={2011},
      publisher={IEEE}
    }
#+END_EXAMPLE

** Semantic Structure from Motion: a Novel Framework for Joint Object
Recognition and 3D Reconstruction
   :PROPERTIES:
   :CUSTOM_ID: semantic-structure-from-motion-a-novel-framework-for-joint-object-recognition-and-3d-reconstruction
   :END:

** Semantic structure from motion with object and point interactions
   :PROPERTIES:
   :CUSTOM_ID: semantic-structure-from-motion-with-object-and-point-interactions
   :END:

* Object Recognization
  :PROPERTIES:
  :CUSTOM_ID: object-recognization
  :END:

** Mask r-cnn
   :PROPERTIES:
   :CUSTOM_ID: mask-r-cnn
   :END:

- [[https://github.com/qixuxiang/mask_rcnn_ros][Github-qixuxiang/mask_rcnn_ros]]
  with ROS

#+BEGIN_EXAMPLE
    @inproceedings{he2017mask,
      title={Mask r-cnn},
      author={He, Kaiming and Gkioxari, Georgia and Doll{\'a}r, Piotr and Girshick, Ross},
      booktitle={Computer Vision (ICCV), 2017 IEEE International Conference on},
      pages={2980--2988},
      year={2017},
      organization={IEEE}
    }
#+END_EXAMPLE

** 2010-Model globally, match locally: Efficient and robust 3D object
recognition
   :PROPERTIES:
   :CUSTOM_ID: model-globally-match-locally-efficient-and-robust-3d-object-recognition
   :END:

- [[https://github.com/tolgabirdal/ppf_matching][Github-tolgabirdal/ppf_matching]]
-
