* Org Mode
  :PROPERTIES:
  :CUSTOM_ID: org-mode
  :END:

** Extracting sourcecode
   :PROPERTIES:
   :CUSTOM_ID: extracting-sourcecode
   :END:

- Refer to
  [[http://orgmode.org/manual/Extracting-source-code.html][ExtractingCode]]
  [C-c C-l: edit the url link]

*** Header arguments
    :PROPERTIES:
    :CUSTOM_ID: header-arguments
    :END:

- /:tangle no/ By default, Org does not tangle the src code block on
  export.
- /:tangle yes/ Org extracts the contents of the code block for the
  tangled output. By default, the output file name is the same as the
  Org file but with a file extension derived from the language
  identifier of the src code block.
- /:tangle filename/ Override the default file name with this one for
  the tangled output.

** Functions
   :PROPERTIES:
   :CUSTOM_ID: functions
   :END:

- /org-babel-tangle/ Tangle the current file. Bound to =C-c C-v t=. With
  prefix argument only tangle the current src code block.

- /org-babel-tangle-file/ Choose a file to tangle. Bound to =C-c C-v f=.
  *** Hooks
- /org-babel-post-tangle-hook/ This hook runs from within code tangled
  by org-babel-tangle, making it suitable for post-processing,
  compilation, and evaluation of code in the tangled files. Jumping
  between code and Org

Debuggers normally link errors and messages back to the source code. But
for tangled files, we want to link back to the Org file, not to the
tangled source file. To make this extra jump, Org uses
org-babel-tangle-jump-to-org function with two additional source code
block header arguments: One, set padline (see padline) to true (the
default setting). Two, set comments (see comments) to link, which makes
Org insert links to the Org file.

* Questions
  :PROPERTIES:
  :CUSTOM_ID: questions
  :END:

** /bin/bash：markdown：command not found
   :PROPERTIES:
   :CUSTOM_ID: binbashmarkdowncommand-not-found
   :END:

Problem:

#+BEGIN_EXAMPLE
    / bin / bash：markdown：command not found
#+END_EXAMPLE

Solutions:

Refer to: https://codeday.me/bug/20180112/116381.html
=(custom-set-variables   '(markdown-command "/usr/local/bin/pandoc"))=
## Reference - [[http://orgmode.org/manual/index.html][ORG Manual]]
