* Vuforia
** Get Started
- Get SDK: [[https://developer.vuforia.com/downloads/sdk][Download for Android/ios/uwp/unity
]]- [[https://library.vuforia.com/articles/Solution/Getting-Started-with-Vuforia-for-Unity-Development][How to install the vuforia unity extension]]

* Kudan
** Introduction
Official Website: https://www.kudan.eu/
Development license: https://wiki.kudan.eu/Development_License_Keys 
Wiki: https://wiki.kudan.eu/Main_Page 
** Samples
Some Kudan samples can be downloaded for here: https://www.kudan.eu/demo/
The source code can be accessed from: https://github.com/kudan-eu 
** Demo: Simple-Samples-Android
Github:  https://github.com/kudan-eu/Simple-Samples-Android
How to use KudanAR framework with kudan demo: https://wiki.kudan.eu/Getting_started#Android
* Some Useful Stuff
** How to git with .unity scence file
- serialization asset/prefab object
1. Switch to Visible Meta Files in Editor
  => Project Settings
  => Editor:  Version Control Mode
2. Switch to Force Text in Editor  Project Settings  Editor
  =>  Asset Serialization Mode
3. Save scene and project from File menu
- [[http://kihira.uk/unity-and-git-getting-them-to-play-nicely/][Unity and Git: Getting them to play nicely]]
- Unit Smart Merge: [[https://docs.unity3d.com/Manual/SmartMerge.html][SmartMerge]]
- Setting up UnityYAMLMerge
Now that UnityYAMLMerge is setup, we need to tell Git to use it for resolving conflicts. This again heavily depends upon how you interact with Git so your experience may vary.

Check [[https://docs.unity3d.com/Manual/SmartMerge.html][here]] first to see if there is a way already listed on setting it up (Ignore the Git section). If it’s listed, follow the instructions and you’re done!
If you wish to use command line Git or another tool, read the rest of this section.
Go to your user home directory (For windows, this is C:/Users/<username>/)
Open the .gitconfig file with a text editor
Paste the following at the end of the file, replacing the sections in <>
#+BEGIN_SRC shell
[merge]
	tool = unityyamlmerge
[mergetool "unityyamlmerge"]
	trustExitCode = false
	keepTemporaries = true
	keepBackup = false
	path = <Unity Install Location>/Editor/Data/Tools/UnityYAMLMerge.exe
	cmd = \"<Unity Install Location>/Editor/Data/Tools/UnityYAMLMerge.exe\" merge -p "$BASE" "$REMOTE" "$LOCAL" "$MERGED"
  #+END_SRC
** gitignore file
### Unity ###
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/

# Autogenerated VS/MD solution and project files
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj

# Unity3D generated meta files
*.pidb.meta

# Unity3D Generated File On Crash Reports
sysinfo.txt
*.orig
#+END_SRC











